baseurl: '/NHSFCAI'
permalink: pretty
title: 'NHS Fellowship in Clinical AI'

logo:
  mobile: "/images/logo/fcai_logo.png"
  mobile_height: "32px"
  mobile_width: "90px"
  desktop: "/images/logo/fcai_logo.png"
  desktop_height: "32px"
  desktop_width: "90px"

home:
  limit_services: 6

collections:
  team:
    output: true
  fellow:
    output: true
  faculty:
    output: true

defaults:

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
